# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b1f466695ccc3ea62cfd2b4065b3008925c68a6c93278a296865ca905be5e9a1c3c5e95bbb99cb7942637a851530cf65e73fbb9089e5046e910934d7bf0bf93

test:
  secret_key_base: 9f396f405299fb684d5f417aabec125da9a1065bf57e9108911f03b7a7ecc630ed986709e5c073ae16aa199f73e6ece4e9dac167712231070b297f7c306cd46f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
